.idea/misc.xml, build.gradle, database.sql, src/main/java/org/scoula/config/RootConfig.java, src/main/java/org/scoula/config/ServletConfig.java, src/main/java/org/scoula/transactions/controller/TransactionController.java, src/main/java/org/scoula/transactions/domain/Transaction.java, src/main/java/org/scoula/transactions/dto/TransactionDTO.java, src/main/java/org/scoula/transactions/dto/TransactionDetailDTO.java, src/main/java/org/scoula/transactions/exception/TransactionNotFoundException.java, src/main/java/org/scoula/transactions/mapper/TransactionMapper.java, src/main/java/org/scoula/transactions/service/TransactionService.java, src/main/java/org/scoula/transactions/service/TransactionServiceImpl.java, src/main/java/org/scoula/transactions/util/RuleBasedAnalyzer.java, src/main/resources/org/scoula/transactions/mapper/TransactionMapper.xml
거래 내역 조회 API 구현
특정 유저 ID에 따른 거래내역 리스트 조회 (거래일 기준 내림차순)
GET /api/users/{userId}/transactions
거래 ID로 상세정보 조회
GET /api/transactions/{id}
상세 정보 조회 시 소비 분석 내용 없으면 rule-based 에 의해 최초 1회만 분석 후 db 저장
→ 분석 없으면 rule-engine 호출 → 분석 내용 생성 코드 미완성
→ 결과 저장 (update)
→ 포함된 DTO 응답
특정 계좌 ID에 따른 거래내역 리스트 조회
GET /api/accounts/{accountId}/transactions
closes #8
=> feat: 거래 내역 조회 기능 추가

database.sql, src/main/java/org/scoula/challenge/controller/ChallengeController.java, src/main/java/org/scoula/challenge/domain/Challenge.java, src/main/java/org/scoula/challenge/dto/ChallengeCreateRequestDTO.java, src/main/java/org/scoula/challenge/dto/ChallengeCreateResponseDTO.java, src/main/java/org/scoula/challenge/enums/ChallengeStatus.java, src/main/java/org/scoula/challenge/enums/ChallengeType.java, src/main/java/org/scoula/challenge/exception/ChallengeDurationTooShortException.java, src/main/java/org/scoula/challenge/exception/ChallengeGoalTooSmallException.java, src/main/java/org/scoula/challenge/exception/ChallengeLimitExceededException.java, src/main/java/org/scoula/challenge/exception/ChallengePasswordFormatException.java, src/main/java/org/scoula/challenge/exception/ChallengePasswordRequiredException.java, src/main/java/org/scoula/challenge/exception/ChallengeStartTooLateException.java, src/main/java/org/scoula/challenge/mapper/ChallengeMapper.java, src/main/java/org/scoula/challenge/service/ChallengeService.java, src/main/java/org/scoula/challenge/service/ChallengeServiceImpl.java, src/main/java/org/scoula/config/RootConfig.java, src/main/java/org/scoula/config/ServletConfig.java, src/main/java/org/scoula/user/mapper/UserMapper.java, src/main/resources/org/scoula/challenge/mapper/ChallengeMapper.xml, src/main/resources/org/scoula/user/mapper/UserMapper.xml
챌린지 생성 API 구현
1. challenge domain, controller, dto, service, mapper, enums 생성 챌린지 타입 선택 시, enums 에 정의된 값만 허용하도록 적용
2. 챌린지 생성시 일어날 수 있는 여러 예외 경우를 추가
> 기간이 너무 짧은 경우 (3일 이내)
> 목표 금액이 너무 작은 경우 (1000원 이내)
> 챌린지를 이미지 3개 참여중인 경우
> 비밀번호가 숫자 4자리가 아닌 경우
> 비밀번호 입력 안 한 경우
> 챌린지 시작일이 생성일 기준 일주일 보다 먼 경우
3. config 파일에 챌린지 경로 입력 완료
4. 챌린지 생성 응답시, 데이터에 유저 닉네임 포함되도록 수정
-> UserMapper , UserMapper.xml 에 닉네임 조회하는 추가
5. 챌린지 생성시, user challenge 테이블에도 추가 
- closes #58
=> feat: 챌린지 생성 API 추가

src/main/java/org/scoula/challenge/controller/ChallengeController.java, src/main/java/org/scoula/challenge/dto/ChallengeJoinRequestDTO.java, src/main/java/org/scoula/challenge/enums/ChallengeStatus.java, src/main/java/org/scoula/challenge/exception/join/ChallengeAlreadyJoinedException.java, src/main/java/org/scoula/challenge/exception/join/ChallengeFullException.java, src/main/java/org/scoula/challenge/exception/join/ChallengeLimitExceededException.java, src/main/java/org/scoula/challenge/exception/join/ChallengePasswordMismatchException.java, src/main/java/org/scoula/challenge/exception/join/ChallengeStatusException.java, src/main/java/org/scoula/challenge/exception/join/InvalidChallengeTypeJoinException.java, src/main/java/org/scoula/challenge/mapper/ChallengeMapper.java, src/main/java/org/scoula/challenge/service/ChallengeService.java, src/main/java/org/scoula/challenge/service/ChallengeServiceImpl.java, src/main/resources/org/scoula/challenge/mapper/ChallengeMapper.xml
챌린지 참여 로직 보완 및 참여 제한/예외/보안 처리 개선
- 개인 챌린지(PERSONAL) 참여 시도 시 예외 발생하도록 서버 차단 로직 추가
- 그룹 챌린지(GROUP) 및 공통 챌린지(COMMON)만 참여 가능
- 유저가 챌린지 타입별로 최대 3개까지만 참여 가능하도록 제한
- 모집 상태가 아닌 챌린지에 참여 시도하면 예외 처리
- 그룹 챌린지 비밀번호 검증 추가 (불일치/누락 예외 처리)
- 참여 인원이 가득 찬 경우 예외 처리 및 상태를 CLOSED로 자동 변경
- 참여 API에서 비밀번호를 query → body 로 전달 방식 변경 (보안 강화)
- 관련 예외 클래스를 다음과 같이 분리:
- ChallengeAlreadyJoinedException
- ChallengeLimitExceededException
- ChallengeFullException
- ChallengeStatusException
- ChallengePasswordMismatchException
- InvalidChallengeTypeJoinException
Closes #73
=> feat: 챌린지 참여 신청 API 구현

.idea/artifacts/Gradle___org_scoula___backend_1_0_SNAPSHOT_war__exploded_.xml, .idea/workspace.xml, build.gradle, src/main/java/org/scoula/config/RootConfig.java, src/main/java/org/scoula/user/domain/UserStatus.java, src/main/java/org/scoula/user/dto/UserResponseDTO.java, src/main/java/org/scoula/user/enums/UserLevel.java, src/main/java/org/scoula/user/exception/signup/NicknameGenerationException.java, src/main/java/org/scoula/user/mapper/UserStatusMapper.java, src/main/java/org/scoula/user/service/UserServiceImpl.java, src/main/java/org/scoula/user/util/NicknameGenerator.java, src/main/resources/org/scoula/user/mapper/UserStatusMapper.xml
- 회원가입 시 닉네임 자동 생성 및 초기 레벨 설정 기능 구현
- GPT API를 활용해 '{동사}하는{동물}' 형태의 랜덤 닉네임 생성
- 생성된 닉네임 중복 검사 후 user_status 테이블에 저장
- 초기 레벨 "금융새싹" 저장
- GPT 호출 실패 시 fallback 닉네임 생성 로직 구현
- UserResponseDTO에 nickname, level 필드 추가
- 
- closes #76
=> feat: 회원가입 시 닉네임 및 레벨 자동 생성 기능 추가

src/main/java/org/scoula/transactions/controller/LedgerController.java, src/main/java/org/scoula/transactions/dto/LedgerCategoryUpdateDto.java, src/main/java/org/scoula/transactions/dto/LedgerMemoUpdateDto.java, src/main/java/org/scoula/transactions/mapper/LedgerMapper.java, src/main/java/org/scoula/transactions/service/LedgerEditService.java, src/main/resources/org/scoula/transactions/mapper/LedgerMapper.xml
가계부 항목 편집 기능 구현 (거래내역의 카테고리 및 메모 수정 API 추가)
→ 카테고리 수정 PATCH API 구현
→ 메모 등록/수정 PATCH API 구현
Swagger 문서 테스트 및 응답 확인 완료
closes #103
=> feat: 거래내역 카테고리/메모 수정 기능 추가

database.sql, src/main/java/org/scoula/challenge/controller/ChallengeController.java, src/main/java/org/scoula/challenge/dto/ChallengeResultResponseDTO.java, src/main/java/org/scoula/challenge/enums/ChallengeResultType.java, src/main/java/org/scoula/challenge/mapper/ChallengeMapper.java, src/main/java/org/scoula/challenge/service/ChallengeService.java, src/main/java/org/scoula/challenge/service/ChallengeServiceImpl.java, src/main/resources/org/scoula/challenge/mapper/ChallengeMapper.xml
챌린지 결과 확인 기능을 위한 API 3종을 구현하고 챌린지 상세 조회 흐름에 반영하였습니다.
- 챌린지 결과 데이터 조회 API (`GET /api/challenge/{id}/result`)
- 챌린지 결과 확인 처리 API (`PATCH /api/challenge/{id}/result/confirm`)
- 결과 미확인 챌린지 존재 여부 확인 API (`GET /api/challenge/has-unconfirmed`)
- DTO 및 Mapper, 서비스, 컨트롤러 계층까지 로직 구현 완료
- 포인트 지급 및 주식 추천 데이터는 별도 API 또는 confirm 시점에서 연동 예정
- closes #93
=> feat: 챌린지 결과 조회 및 확인 관련 API 구현

database.sql, src/main/java/org/scoula/account/controller/AccountController.java, src/main/java/org/scoula/account/domain/Account.java, src/main/java/org/scoula/account/mapper/AccountMapper.java, src/main/java/org/scoula/account/service/AccountService.java, src/main/java/org/scoula/account/service/AccountServiceImpl.java, src/main/java/org/scoula/card/controller/CardController.java, src/main/java/org/scoula/card/domain/Card.java, src/main/java/org/scoula/card/mapper/CardMapper.java, src/main/java/org/scoula/card/service/CardService.java, src/main/java/org/scoula/card/service/CardServiceImpl.java, src/main/java/org/scoula/common/exception/ForbiddenException.java, src/main/resources/org/scoula/account/mapper/AccountMapper.xml, src/main/resources/org/scoula/card/mapper/CardMapper.xml
사용자가 연동된 계좌 또는 카드를 해제(삭제)할 수 있도록
account, card 리소스에 대한 삭제 API를 구현합니다.
삭제는 완전 삭제가 아닌 soft-delete 방식으로 처리합니다.
> 컬럼 없으면 BOOLEAN DEFAULT TRUE로 추가
> 기본값은 true, 삭제 시 false 처리
> 기존 API에서 is_active = true 조건 추가 (예: 잔액 조회, 거래내역 등)
> 해당 계좌의 is_active 값을 false로 업데이트
> 이미 비활성화된 계좌일 경우 예외 처리 or 무시
> 해당 카드의 is_active 값을 false로 업데이트
> 이미 비활성화된 카드일 경우 예외 처리 or 무시
closes #106
=> feat: 계좌/카드 개별 삭제 기능 추가

database.sql, src/main/java/org/scoula/challenge/rank/controller/ChallengeCoinRankController.java, src/main/java/org/scoula/challenge/rank/controller/ChallengeRankController.java, src/main/java/org/scoula/challenge/rank/controller/ChallengeRankTestController.java, src/main/java/org/scoula/challenge/rank/dto/ChallengeCoinRankResponseDTO.java, src/main/java/org/scoula/challenge/rank/dto/ChallengeCoinRankSnapshotResponseDTO.java, src/main/java/org/scoula/challenge/rank/dto/ChallengeRankResponseDTO.java, src/main/java/org/scoula/challenge/rank/dto/ChallengeRankSnapshotResponseDTO.java, src/main/java/org/scoula/challenge/rank/mapper/ChallengeCoinRankMapper.java, src/main/java/org/scoula/challenge/rank/mapper/ChallengeRankMapper.java, src/main/java/org/scoula/challenge/rank/scheduler/ChallengeCoinRankScheduler.java, src/main/java/org/scoula/challenge/rank/scheduler/ChallengeRankScheduler.java, src/main/java/org/scoula/challenge/rank/service/ChallengeCoinRankService.java, src/main/java/org/scoula/challenge/rank/service/ChallengeCoinRankServiceImpl.java, src/main/java/org/scoula/challenge/rank/service/ChallengeRankService.java, src/main/java/org/scoula/challenge/rank/service/ChallengeRankServiceImpl.java, src/main/java/org/scoula/challenge/rank/util/ChallengeParticipantProvider.java, src/main/java/org/scoula/challenge/rank/util/ChallengeParticipantProviderImpl.java, src/main/java/org/scoula/config/RootConfig.java, src/main/java/org/scoula/config/ServletConfig.java, src/main/resources/org/scoula/challenge/rank/mapper/ChallengeCoinRankMapper.xml, src/main/resources/org/scoula/challenge/rank/mapper/ChallengeRankMapper.xml
공통 챌린지 진행률 랭킹, 누적 코인 랭킹 기능 전면 구현 및 관련 테이블 신규 추가 작업입니다.  
랭킹 계산 스케줄러, 조회/저장 API, 테스트용 API까지 전체 흐름을 반영했으며, SqlSessionTemplate 제거 후 Mapper 방식으로 리팩토링했습니다.
- 랭킹 저장용 테이블 4종 추가 (DDL)
- `challenge_rank`
- `challenge_rank_snapshot`
- `challenge_coin_rank`
- `challenge_coin_rank_snapshot`
- 공통 챌린지 진행률 랭킹 기능
- 실시간 랭킹 계산 및 저장
- 월별 스냅샷 저장
- Top5 + 내 랭킹 조회 API
- 랭킹 확인 여부 반영 API
- 누적 코인 랭킹 기능
- 실시간 누적 포인트 기반 랭킹 계산
- 월별 스냅샷 저장
- Top5 + 내 랭킹 조회 API
- 랭킹 확인 여부 반영 API
- 랭킹 계산 스케줄러 2종 구현
- 수동 실행용 테스트 API 추가
- SqlSessionTemplate 제거 및 ChallengeRankMapper 기반으로 리팩토링 완료
- 추후 랭킹 리셋(초기화) 타이밍 및 월별 보상 로직과의 연동 방식은 어떻게 가져갈지 논의가 필요합니다.
- closes #101
=> feat: 챌린지 공통/코인 랭킹 기능 구현

src/main/java/org/scoula/avatar/controller/AvatarController.java, src/main/java/org/scoula/avatar/mapper/AvatarMapper.java, src/main/java/org/scoula/avatar/service/AvatarService.java, src/main/java/org/scoula/avatar/service/AvatarServiceImpl.java, src/main/resources/org/scoula/avatar/mapper/AvatarMapper.xml, src/main/resources/org/scoula/coin/mapper/CoinMapper.xml
아바타 의상 구매 시 재화를 사용하는 로직을 리팩토링했습니다.
- **재화 소비 로직 재사용**
기존에 아바타 기능 내부에 별도로 존재하던 재화 소비 코드를 공용 coin 패키지의 기능을 사용하도록 변경하여 코드의 중복을 제거하고 일관성을 높였습니다.
- **Mapper 기능 수정**
coinMapper의 subtract 메소드가 순수하게 금액을 차감하는 역할만 수행하도록 수정했습니다
closes #126
=> refactor: 아바타 기능 재화소비코드 리펙토링

src/main/java/org/scoula/alarm/controller/AlarmController.java, src/main/java/org/scoula/avatar/controller/AvatarController.java, src/main/java/org/scoula/quiz/controller/QuizController.java, src/main/java/org/scoula/quiz/dto/QuizSubmitRequestDTO.java, src/main/java/org/scoula/quiz/service/QuizService.java, src/main/java/org/scoula/quiz/service/QuizServiceImpl.java, src/main/java/org/scoula/security/account/domain/CustomUserDetails.java, src/main/java/org/scoula/security/account/dto/AuthResultDTO.java, src/main/java/org/scoula/security/handler/LoginSuccessHandler.java, src/main/java/org/scoula/security/service/CustomUserDetailsService.java, src/main/java/org/scoula/user/mapper/UserStatusMapper.java, src/main/resources/org/scoula/user/mapper/UserStatusMapper.xml
closes #130
컨트롤로 파라미터와 로그인 반환값 수정
컨트롤러에서 이전에 수정하지 못한 Long id 파라미터들을 발견
security context의 principal 참조하도록 교체
로그인 성공 핸들러에 닉네임도 반환하도록 수정
closes #130
=> fix: 로그인 시 응답수정 및 파라미터 수정

src/main/java/org/scoula/account/controller/AccountController.java, src/main/java/org/scoula/account/dto/AccountDto.java, src/main/java/org/scoula/account/service/AccountService.java, src/main/java/org/scoula/account/service/AccountServiceImpl.java, src/main/java/org/scoula/card/controller/CardController.java, src/main/java/org/scoula/card/service/CardService.java, src/main/java/org/scoula/card/service/CardServiceImpl.java, src/main/java/org/scoula/monthreport/controller/MonthReportController.java, src/main/java/org/scoula/transactions/controller/AccountTransactionController.java, src/main/java/org/scoula/transactions/controller/CardTransactionController.java, src/main/java/org/scoula/transactions/controller/LedgerController.java, src/main/java/org/scoula/transactions/domain/CardTransaction.java
- 컨트롤러 전반에 걸쳐 userId 하드코딩 및 임시값 제거
- JWT 인증 기반 Spring Security 표준(@AuthenticationPrincipal) 방식으로 유저 정보 주입 통일
- 기존 Authorization 헤더에서 직접 토큰 파싱 및 userId 추출 → **@AuthenticationPrincipal CustomUserDetails user** 방식으로 일원화
- 서비스 및 도메인 로직에서 하드코딩된 userId(예: 1L 등) 제거, 실제 로그인 유저 정보 사용하도록 리팩토링
- 각종 API(userId path/requestParam 등)에서 userId 파라미터 제거, 인증 객체에서 주입
- 코드 내 임시 유저 식별자, 테스트 계정 등 관련 부분 전부 삭제
- JWT 기반 인증/인가 로직을 전담 필터에서 일원 처리하도록 개선
- [] 리뷰어 n명 이상 승인 완료
- 없음
- closes #139
=>  JWT 기반 유저 식별 적용 및 userId 임시값 제거

src/main/java/org/scoula/challenge/controller/ChallengeController.java, src/main/java/org/scoula/challenge/service/ChallengeService.java, src/main/java/org/scoula/challenge/service/ChallengeServiceImpl.java, src/main/java/org/scoula/security/filter/JwtAuthenticationFilter.java
* JWT 액세스 토큰 전달 방식을 `@AuthenticationPrincipal` 기반으로 통일하여 보안성 및 유지보수성 개선
* 주식 추천 로직에서 외부 API 호출 제거, 내부 `StockService` 호출로 변경
* 증권 API 토큰 발급 및 재시도 로직을 `StockServiceImpl`에서 일원화
* 추천 주식 로직의 불필요한 null 비교 오류 수정
* **ChallengeController / ChallengeServiceImpl**
* `accessToken` 파라미터 제거 및 컨트롤러에서 `userId`만 서비스로 전달
* 외부 증권 API 직접 호출 제거, 내부 `StockService` 호출로 변경
* **StockServiceImpl**
* 사용자 증권 API 토큰 조회/검증/재발급 로직 통합 (`sendPostRequestWithUserId` 메서드)
* 401·419 응답 시 토큰 재발급 후 1회 재시도, 429 응답 시 지수 백오프 적용
* **추천 주식 로직 개선**
* int 타입의 불필요한 null 비교 제거
* `price > 0 && price <= savedAmount` 조건을 만족하는 종목 중 최댓값 선정
- 시큐리티 허용 URI 설정 수정도 필요함
- closes #148
=> refactor: JWT 전달 방식 개선 및 주식 추천 로직 수정

src/main/java/org/scoula/security/config/SecurityConfig.java, src/main/java/org/scoula/user/util/NicknameGenerator.java
스프링 시큐리티 기본 정책을 강화하고, OkHttp 응답 자원 미해제로 인한 `connection leaked` 경고를 해결했습니다.
공개 API 화이트리스트를 명확히 하고 로그인 필터 URL을 고정하여 불필요한 인증 시도를 방지했습니다.
* **SecurityConfig**
* 공개 허용 경로(permitAll) 명시
* POST `/api/user/signup`
* GET `/api/user/email-check`
* POST `/api/user/password-reset`
* POST `/api/auth/login`
* GET `/api/auth/test-login`
* `JwtEmailPasswordAuthenticationFilter.setFilterProcessesUrl("/api/auth/login")` 적용
* `anyRequest().authenticated()`로 기본 차단 정책 적용
* `web.ignoring` 최소화(정적/Swagger/favicon만 제외)
* CORS에 프론트 도메인만 허용(와일드카드 제거), credentials=true 시 브라우저 제약 대응
* CSRF 비활성화 유지 → 프론트의 `/csrf` 호출 불필요
* **NicknameGenerator**
* OkHttpClient 싱글턴 재사용으로 커넥션 재활용
* try-with-resources로 Response/Body를 안전하게 close → connection leaked 경고 제거
* 타임아웃 설정 추가(connect/read/write)
* **기타**
* favicon 404 로그 소음 …
=> fix: 보안 기본정책 강화 및 OkHttp 연결 누수 수정

src/main/java/org/scoula/security/config/SecurityConfig.java
- SecurityConfig에 스케줄러 테스트용 API 호출 허용 경로 추가
- `/api/challenge/scheduler/**` GET 요청을 permitAll()로 설정
- closes #168
=> fix: 스케줄러 테스트용 API SecurityConfig에 permitAll 경로 추가

src/main/java/org/scoula/security/config/SecurityConfig.java, src/main/java/org/scoula/security/filter/JwtAuthenticationFilter.java, src/main/java/org/scoula/security/handler/CustomAuthenticationEntryPoint.java
JWT 인증 실패 시 원인을 명확히 파악할 수 있도록 서버 로그와 응답 메시지를 강화하고, 공개 경로에서는 불필요한 JWT 필터 검사를 제외하도록 개선했습니다.
- **인증 실패 로깅 강화**
- CustomAuthenticationEntryPoint에 요청 URI, Authorization 헤더 존재 여부/값 일부, 예외 메시지 로깅 추가
- 필터에서 설정한 auth_exception_message를 우선 사용하여 응답 메시지에 상세 사유 포함
- **JwtAuthenticationFilter 개선**
- 토큰 없음, 형식 오류, 블랙리스트, 검증 실패, 컨텍스트 실패 등 상황별로 로그 및 상세 사유 설정
- request attribute를 통해 EntryPoint로 실패 사유 전달
- shouldNotFilter 구현으로 공개 경로(API 로그인, 토큰 재발급, Swagger, 정적 리소스, 스케줄러) 요청 시 필터 스킵
- **SecurityConfig 수정**
- /api/auth/refresh permitAll 추가
- CORS exposedHeaders에 Authorization 추가
- 현재 auth_exception_message에 담기는 상세 사유를 운영 환경에서도 그대로 응답에 내려도 되는지(보안 정책 확인 필요)
- shouldNotFilter에 포함된 경로 외에 추가로 제외할 엔드포인트가 있는지
- closes #171
=> feat: JWT 인증 실패 원인 추적 로깅 강화 및 공개 경로 필터 제외 처리

src/main/java/org/scoula/security/config/SecurityConfig.java, src/main/java/org/scoula/security/handler/LoginSuccessHandler.java, src/main/java/org/scoula/security/util/CookieUtil.java, src/main/java/org/scoula/user/controller/AuthController.java
JWT 토큰 발급·재발급 방식을 쿠키 기반(RT) + 헤더 기반(AT)으로 변경하여 보안성과 표준성을 강화
- Refresh Token → httpOnly 쿠키로 전달
- Access Token → Authorization 헤더로 전달
- 요청 시 브라우저에서 RT 자동 전송
- 응답에서 AT는 Authorization 헤더로만 전달
- allowCredentials(true) 적용
- http://localhost:5173 허용
- SameSite=Lax, Secure=false로 환경에 맞게 쿠키 설정
기존 JSON 응답의 토큰 필드 제거
프론트에서 RT를 JS로 접근하지 않도록 구조 변경 대비
- closes #176
=> feat: 토큰 발급 방식을 쿠키/헤더 기반으로 전면 전환

src/main/java/org/scoula/nhapi/dto/NhAccountTransactionResponseDto.java, src/main/java/org/scoula/nhapi/dto/NhCardTransactionResponseDto.java, src/main/java/org/scoula/nhapi/parser/NhCardParser.java, src/main/java/org/scoula/nhapi/service/NhAccountServiceImpl.java, src/main/java/org/scoula/nhapi/service/NhCardServiceImpl.java, src/main/java/org/scoula/transactions/domain/CardTransaction.java, src/main/java/org/scoula/transactions/mapper/AccountTransactionMapper.java, src/main/java/org/scoula/transactions/mapper/CardTransactionMapper.java, src/main/java/org/scoula/transactions/service/AccountTransactionServiceImpl.java, src/main/java/org/scoula/transactions/service/CardTransactionServiceImpl.java, src/main/resources/org/scoula/transactions/mapper/AccountTransactionMapper.xml, src/main/resources/org/scoula/transactions/mapper/CardTransactionMapper.xml
- 계좌/카드 **동기화 안정화**: 증분 시작일을 “마지막 거래일 + 1일”로 통일하고 중복키 강化
- NH API 응답 없을 때 **더미 데이터 고도화**(기간 맞춤, 계좌/유저별 시드, 현실적 패턴)
- 카드 승인내역 파싱/저장 **타입 정합성** 확보(LocalDateTime/LocalDate)
- **approved_at NULL** / **ledger.source_id NULL** 발생 원인 제거  
(useGeneratedKeys로 거래 PK 주입, ledger.source_id=거래PK)
- `AccountTransactionServiceImpl`
- 기본 동기화는 **증분 모드**로 수행 (`getNextStartDate=마지막+1일`, 없으면 3개월 전)
- 중복 체크 키를 `userId + accountId + tuNo`로 강화
- 수입 거래만 ledger 반영(카테고리 10 “이체”), from~to 로그 출력
- `NhAccountServiceImpl`
- NH 응답 `A0090` 혹은 빈 Rec 시 **기간 기반 더미 생성**(`createDummyTransactions`)
- 더미는 from~to(yyyyMMdd) **엄수**, 계좌/유저 기반 시드로 **재현성 보장**
- 급여/고정비/일상소비 패턴, 금액/가맹점/메모 다양화
- tuNo를 `(accountId, 날짜, 인덱스)` 조합의 **결정적 키**로 생성
- `NhAccountTransactionResponseDto`
- `parseDateTime` 보강(HHmm/HHmmss 변형 대응)
- 안정적 tuNo …
=> refactor: 계좌/카드 동기화 안정화

Dockerfile
dockerfile venv 사용방식으로 수정
```
RUN apt-get update && \
apt-get install -y --no-install-recommends python3 python3-pip python3-venv && \
python3 -m venv /opt/venv && \
/opt/venv/bin/pip install --upgrade pip && \
ln -sf /opt/venv/bin/python /usr/local/bin/python && \
rm -rf /var/lib/apt/lists/*
ENV PATH="/opt/venv/bin:${PATH}"
```
=> fix: dockerfile venv 사용방식으로 수정

src/main/java/org/scoula/challenge/dto/StockRecommendationDTO.java, src/main/java/org/scoula/challenge/mapper/ChallengeMapper.java, src/main/java/org/scoula/challenge/service/ChallengeServiceImpl.java, src/main/java/org/scoula/coin/controller/CoinController.java, src/main/java/org/scoula/coin/dto/CoinStatusResponseDTO.java, src/main/java/org/scoula/coin/enums/CoinType.java, src/main/java/org/scoula/coin/mapper/CoinMapper.java, src/main/java/org/scoula/coin/service/CoinService.java, src/main/java/org/scoula/coin/service/CoinServiceImpl.java, src/main/java/org/scoula/user/service/UserServiceImpl.java, src/main/resources/org/scoula/challenge/mapper/ChallengeMapper.xml, src/main/resources/org/scoula/coin/mapper/CoinMapper.xml
* **회원가입 시 축하금 100P 자동 지급**: 잔액·누적 반영(월누적 제외) + `coin_history` 기록
* **`registerUser` 트랜잭션 처리**로 초기화/지급/부가 데이터 생성 일관성 보장
* (이전 작업 포함, 상세 기술)
* **챌린지**: 진행중 판정 통일, 결과 처리 2단계(계산/지급 분리), 요약 갱신 시 `updated_at` 관리
* **코인**: `/api/coin/status` 도입으로 코인 스냅샷 제공, `coin_history` 타입 확장
* **신규 지급 메서드(월누적 제외)**
* `CoinMapper.addCoinAmountExceptMonthly(userId, amount)` 추가
* `CoinMapper.xml`에 `amount`, `cumulative_amount`만 증가하도록 UPDATE 문 추가
* 목적: \*\*축하금은 월누적(챌린지 전용)\*\*에 포함하지 않기 위함
* **코인 내역 기록**
* 축하금 지급 시 `coin_history`에 `type='plus'`, `coin_type='WELCOME'` 기록
* DB 마이그레이션: `coin_history.coin_type`에 `WELCOME` 추가
```sql
ALTER TABLE coin_history
MODIFY COLUMN coin_type ENUM('QUIZ','CHALLENGE','AVATAR','GIFTICON','WELCOME') NOT NULL;
```
* **코인 스냅샷 API**
* `GET /api/coin/status` 추가
* `CoinStatusResponseDTO …
=> fix: 챌린지, 코인, 회원가입 등 다양하게 수정

src/main/java/org/scoula/challenge/service/ChallengeServiceImpl.java, src/main/resources/org/scoula/challenge/mapper/ChallengeMapper.xml
* 개인/그룹 챌린지 “최대 3개” 참여 제한이 뚫리던 이슈 수정
* 진행중 카운트 쿼리에 `CLOSED` 상태 포함
* (선택) 개인 챌린지 생성 시 시작일 기준 상태 분기(`IN_PROGRESS`/`CLOSED`)로 의미론 보강
* `ChallengeMapper.xml`
* `countUserOngoingChallenges` 쿼리에서 진행중 판정 범위를 확대
* 변경: `RECRUITING`, `IN_PROGRESS`, **`CLOSED`** 포함 + `COMPLETED & !result_checked`
* (선택) `ChallengeServiceImpl`
* 개인 챌린지 생성 시 `startDate`가 오늘/과거면 `IN_PROGRESS`, 미래면 `CLOSED`로 저장하도록 분기
* `org/scoula/challenge/mapper/ChallengeMapper.xml`
* *(선택)* `org/scoula/challenge/service/ChallengeServiceImpl.java`
1. 동일 유저로 개인 챌린지 3개 생성 → 4번째 생성 시도
* 기대: `ChallengeLimitExceededException` (400) 발생
2. 그룹 챌린지도 동일 시나리오로 검증
3. 완료되었지만 결과 미확인 챌린지가 있는 경우 카운트에 포함되는지 확인
4. (선택 변경 반영 시) 개인 챌린지 생성 시 시작일에 따라 상태가 `IN_PROGRESS`/`CLOSED`로 적절히 저장되는지 확인
* Swagger 호출 응답 캡처 첨부
* DB 쿼리/카운트 로그 필요 시 추가
* 개인 챌린지 생성 시 상태 …
=> fix: 챌린지 홈 참여중 리스트 조회 로직 및 챌린지 개수 제한 로직 수정

src/main/java/org/scoula/user/controller/UserController.java, src/main/java/org/scoula/user/mapper/UserMapper.java, src/main/java/org/scoula/user/service/UserService.java, src/main/java/org/scoula/user/service/UserServiceImpl.java, src/main/resources/org/scoula/user/mapper/UserMapper.xml
간편비밀번호 생성여부에 따른 특정페이지창 접속 통제를 필요함
이에 간편비밀번호 생성여부 조회 기능 추가기능추가 
user 패키지의 컨트롤러에 /api/user/pin/isCreated 루트 생성
서비스에 isPinCreated 메소드 생성
closes #255
=> feat: 간편비밀번호 생성여부 조회 기능 추가

src/main/resources/org/scoula/challenge/rank/mapper/ChallengeRankMapper.xml
* `user.nickname` 컬럼 참조로 발생한 SQL 오류 수정
* 닉네임은 `user_status.nickname`만 사용하도록 정리
* `ChallengeRankMapper.xml`
* `getCurrentChallengeRanks`:
* `COALESCE(us.nickname, u.nickname)` → **`IFNULL(us.nickname, CONCAT('user#', u.id))`**
* ``cr.`rank` AS `rank` ``로 백틱 유지
* `getChallengeRankSnapshots`:
* 동일하게 **`IFNULL(us.nickname, CONCAT('user#', u.id))`** 사용
* ``crs.`rank` AS `rank` ``로 백틱 유지
* 기타: `u.nickname` 참조 제거 (DB에 해당 컬럼 없음)
* closes #244
=> fix: challenge rank nickname error

src/main/java/org/scoula/challenge/service/ChallengeServiceImpl.java, src/main/java/org/scoula/config/RootConfig.java, src/main/java/org/scoula/security/account/domain/CustomUserDetails.java, src/main/java/org/scoula/security/config/SecurityConfig.java, src/main/java/org/scoula/user/controller/UserController.java, src/main/java/org/scoula/user/domain/User.java, src/main/java/org/scoula/user/enums/UserRole.java, src/main/java/org/scoula/user/service/UserServiceImpl.java, src/main/resources/org/scoula/challenge/rank/mapper/ChallengeRankMapper.xml, src/main/resources/org/scoula/user/mapper/UserMapper.xml
* **\[#246] 유저 권한(Role) 도입**: `user` 테이블에 `role` 컬럼 추가 및 Spring Security 연계.
* **\[#247] 월별 누적 포인트 랭킹(코인 랭킹) 구축**: 스케줄러/이벤트/수동 트리거 기반의 랭킹 산정 파이프라인 추가, API/매퍼/서비스/보안 설정 일괄 반영.
---
* **DB 마이그레이션**
```sql
-- 1) role 컬럼 추가 (기본 USER)
ALTER TABLE `user`
ADD COLUMN `role` VARCHAR(20) NOT NULL DEFAULT 'ROLE_USER' AFTER `gender`;
-- 2) 기존 사용자 기본값 보정
UPDATE `user` SET `role` = 'ROLE_USER' WHERE `role` IS NULL OR `role` = '';
-- (선택) 관리자 지정
-- UPDATE `user` SET `role` = 'ROLE_ADMIN' WHERE email IN ('admin@example.com');
```
* **Security 연계**
* `CustomUserDetails`에서 `role` → `GrantedAuthority` 매핑 확인/보정 (`ROLE_USER`/`ROLE_ADMIN`).
* 운영 시 특정 관리 엔드포인트는 `hasRole("ADMIN")`로 전환 가능.
* **DB 스키마** (이미 운영 DB에 존재 시 스킵)
```sql
CREATE TABLE IF NOT EXISTS `challenge_coin_rank` (
`id` BIGINT NOT NULL …
```
=> fix: challenge point rank, user role add

src/main/java/org/scoula/account/util/BankCatalog.java, src/main/java/org/scoula/monthreport/dto/MonthReportDetailDto.java, src/main/java/org/scoula/monthreport/dto/PatternBannerDto.java, src/main/java/org/scoula/monthreport/service/MonthReportGeneratorImpl.java, src/main/java/org/scoula/monthreport/service/MonthReportReadServiceImpl.java, src/main/java/org/scoula/monthreport/service/PatternBannerMapper.java, src/main/java/org/scoula/monthreport/service/PatternClassifier.java, src/main/java/org/scoula/monthreport/util/CategoryMapper.java, src/main/java/org/scoula/monthreport/util/ChallengeRecommenderEngine.java, src/main/java/org/scoula/monthreport/util/SpendingAnalysisEngine.java
항상 STABLE만 뜨는 문제, 카테고리 키 불일치, 이체/없음 포함으로 인한 비율 왜곡, 평균비교 분모 불일치를 한 번에 정리.
분석/추천 컨텍스트를 KOSIS 키(food/cafe/...) 기준으로 일원화하고, 차트는 한글 라벨 그대로 노출.
추천은 “총지출 절감 / 카테고리 절감” 두 축만 유지하면서 점수 기반으로 2개 정확히 리턴.
=> fix(report): 카테고리 정규화/필터링 통일, 패턴 분류 보정, 평균비교/추천 로직 안정화

src/main/java/org/scoula/account/controller/AccountController.java, src/main/java/org/scoula/account/mapper/AccountMapper.java, src/main/java/org/scoula/account/service/AccountServiceImpl.java, src/main/java/org/scoula/card/controller/CardController.java, src/main/java/org/scoula/card/mapper/CardMapper.java, src/main/java/org/scoula/card/service/CardServiceImpl.java, src/main/java/org/scoula/config/RootConfig.java, src/main/java/org/scoula/nhapi/client/NHApiClient.java, src/main/java/org/scoula/nhapi/parser/NhCardParser.java, src/main/java/org/scoula/nhapi/service/NhAccountServiceImpl.java, src/main/java/org/scoula/nhapi/service/NhCardServiceImpl.java, src/main/java/org/scoula/nhapi/util/AccountBrandingUtil.java, src/main/java/org/scoula/nhapi/util/BankCatalog.java, src/main/java/org/scoula/nhapi/util/CardBrandingUtil.java, src/main/java/org/scoula/nhapi/util/FirstLinkOnboardingService.java, src/main/resources/org/scoula/account/mapper/AccountMapper.xml, src/main/resources/org/scoula/card/mapper/CardMapper.xml, src/main/resources/org/scoula/transactions/mapper/AccountTransactionMapper.xml, src/main/resources/org/scoula/transactions/mapper/CardTransactionMapper.xml
프론트에서 “자산 연동”을 누르면 실제 NH 발급 절차(핀계좌·핀카드·토큰)를 호출하지 않고, 서버가 mock 모드에서 DB에 보관된 핀계좌/핀카드 값을 재사용하여 즉시 등록·동기화가 완료된 것처럼 동작하게 한다.
한 번 저장된 핀계좌/핀카드 값은 **항상 재사용(재발급 생략)**하며, 기본 시드(기본 3계좌+2카드, 필요 시 heavy 5+4)와 거래 더미를 멱등 업서트로 주입한다.
closes 235
=> feat: 자산 초기 목업 연동
