FinPickTeam/FinPickTeam_BE

.github/workflows/deploy.yml
배포 자동화 에러 해결
deploy.yml 에서 env DOCKER_TAG 관련 코드 삭제
- closes #27
=> fix: deploy file error

.github/workflows/deploy.yml
deploy.yml 수정
cd 의 runs-on 수정 : ubuntu-24.04 로 수정
- closes #32
=> fix: deploy cd error

.github/workflows/deploy.yml, .idea/dataSources.xml, src/main/java/org/scoula/config/RootConfig.java, src/main/java/org/scoula/config/ServletConfig.java, src/main/java/org/scoula/dictionary/controller/DictionaryController.java, src/main/java/org/scoula/dictionary/domain/DictionaryVO.java, src/main/java/org/scoula/dictionary/dto/DictionaryDTO.java, src/main/java/org/scoula/dictionary/mapper/DictionaryMapper.java, src/main/java/org/scoula/dictionary/service/DictionaryService.java, src/main/java/org/scoula/dictionary/service/DictionaryServiceImpl.java, src/main/resources/org/scoula/dictionary/mapper/DictionaryMapper.xml
deploy.yml 이름 형식 수정
다빈님 금융 퀴즈 부분 포함
deploy.yml 이름 형식 수정
=> fix: deploy.yml 이름 형식 수정

.github/workflows/deploy.yml
docker tag 이름 잘 가져오도록 합니다
ci에서 가져오는 DOCKER_TAG 값이 잘 받아와지도록 수정
'' -> "" 로 수정
=> fix: deploy file 코드 수정

.github/workflows/deploy.yml
deploy.yml 코드 수정
current_time  -> current-time
=> fix: deploy file

.github/workflows/deploy.yml, Dockerfile, build.gradle
Dockerfile 수정 후 배포 테스트
Dockerfile 수정 사항 main 에 머지
- 관련된 이슈 번호를 연결해주세요. (예: closes #123)
=> [자영] Dockerfile 수정 후 배포 테스트

.idea/artifacts/Gradle___org_scoula___backend_1_0_SNAPSHOT_war__exploded_.xml, .idea/dataSources.local.xml, .idea/workspace.xml, src/main/java/org/scoula/finance/controller/DepositController.java, src/main/java/org/scoula/finance/controller/InstallmentController.java, src/main/java/org/scoula/finance/controller/StockController.java, src/main/java/org/scoula/finance/mapper/DepositMapper.java, src/main/java/org/scoula/finance/service/deposit/DepositServiceImpl.java, src/main/java/org/scoula/finance/service/installment/InstallmentServiceImpl.java, src/main/java/org/scoula/finance/service/stock/StockService.java, src/main/java/org/scoula/finance/service/stock/StockServiceImpl.java, src/main/resources/org/scoula/finance/mapper/DepositMapper.xml
재테크 중복 코드 제거
예금 중복 코드 제거
주식 limit 추가
close #68 
- 관련된 이슈 번호를 연결해주세요. (예: closes #123)
=> refactor: 재테크 중복 코드 제거

database.sql, src/main/java/org/scoula/transactions/controller/AccountTransactionController.java, src/main/java/org/scoula/transactions/controller/CardTransactionController.java, src/main/java/org/scoula/transactions/controller/LedgerController.java, src/main/java/org/scoula/transactions/dto/LedgerDto.java, src/main/java/org/scoula/transactions/mapper/AccountTransactionMapper.java, src/main/java/org/scoula/transactions/mapper/CardTransactionMapper.java, src/main/java/org/scoula/transactions/mapper/LedgerMapper.java, src/main/java/org/scoula/transactions/service/AccountTransactionService.java, src/main/java/org/scoula/transactions/service/AccountTransactionServiceImpl.java, src/main/java/org/scoula/transactions/service/CardTransactionService.java, src/main/java/org/scoula/transactions/service/CardTransactionServiceImpl.java, src/main/java/org/scoula/transactions/service/LedgerService.java, src/main/java/org/scoula/transactions/service/LedgerServiceImpl.java, src/main/resources/org/scoula/transactions/mapper/AccountTransactionMapper.xml, src/main/resources/org/scoula/transactions/mapper/CardTransactionMapper.xml, src/main/resources/org/scoula/transactions/mapper/LedgerMapper.xml
계좌, 카드 거래 내역 조회시 기간 필터 추가
총 거래내역 조회 시 카테고리 필터 추가
카테고리 테이블 추가 및 instance 고정 
closes 86
- 관련된 이슈 번호를 연결해주세요. (예: closes #123)
=> refactor: 거래내역 조회 조건 추가

src/main/java/org/scoula/finance/controller/StockController.java, src/main/java/org/scoula/finance/dto/stock/StockListDto.java, src/main/java/org/scoula/finance/service/stock/StockService.java, src/main/java/org/scoula/finance/service/stock/StockServiceImpl.java, src/main/java/org/scoula/finance/service/stock/python/calcStock.py
주식 추천 로직 오류 수정
파이썬 파일 수정
close #88
=> feat:주식 오류 수정

src/main/java/org/scoula/avatar/service/AvatarServiceImpl.java
level컬럼 수정으로 인한 getter메소드 이름 변경 적용
closes #128
level컬럼 수정으로 인한 getter메소드 이름 변경 적용
level컬럼 수정으로 인한 getter메소드 이름 변경 적용
getAvatarImage() -> getLevelId()로 변경
- [] 리뷰어 n명 이상 승인 완료
closes #141
=> fix: level컬럼 관련 수정

database.sql, src/main/java/org/scoula/quiz/controller/QuizController.java, src/main/java/org/scoula/survey/controller/SurveyController.java, src/main/java/org/scoula/survey/dto/SurveyDTO.java, src/main/java/org/scoula/survey/dto/SurveyRequestDTO.java, src/main/java/org/scoula/survey/service/SurveyService.java, src/main/java/org/scoula/survey/service/SurveyServiceImpl.java, src/main/java/org/scoula/user/service/UserServiceImpl.java
컨트롤러 파라미터 수정 및 초기화 수정
컨프롤러의 파라미터 authentication.principal로 수정
회원가입 시 옷장에서 금융새싹의상의 is_wearing값을 true로 변경
closes #150
=> fix: 컨트롤러 파라미터 수정 및 초기화 수정

src/main/java/org/scoula/survey/controller/SurveyController.java, src/main/java/org/scoula/survey/domain/SurveyVO.java, src/main/java/org/scoula/survey/dto/SurveyDTO.java, src/main/java/org/scoula/survey/dto/SurveyRequestDTO.java, src/main/java/org/scoula/survey/dto/SurveyResponseDTO.java, src/main/java/org/scoula/survey/service/SurveyService.java, src/main/java/org/scoula/survey/service/SurveyServiceImpl.java, src/main/resources/org/scoula/survey/mapper/SurveyMapper.xml
설문조사 응답 및 반환값 수정
설문조사저장 시, 파라미터에 새로운 질문값을 추가
반환값에 투자유형에 대한 설명 추가
closes #107
=> feat: 설문조사 응답 및 반환값 수정

README.md
=> docs: 리드미 수정 후 재배포

README.md, src/main/java/org/scoula/challenge/dto/ChallengeListResponseDTO.java, src/main/java/org/scoula/challenge/service/ChallengeServiceImpl.java
챌린지 파트 백엔드 수정
챌린지 홈 참여중 리스트 조회 로직 및 챌린지 개수 제한 로직 수정
챌린지 리스트 조회시 비밀번호 사용 여부도 응답에 추가
- closes #207 
- closes #209
=> [재배포] dev 수정사항 main 에 반영

database.sql, src/main/java/org/scoula/finance/controller/StockController.java, src/main/java/org/scoula/finance/dto/stock/StockCompareDataDto.java, src/main/java/org/scoula/finance/mapper/StockMapper.java, src/main/java/org/scoula/finance/service/stock/StockService.java, src/main/java/org/scoula/finance/service/stock/StockServiceImpl.java, src/main/resources/org/scoula/finance/mapper/StockMapper.xml
주식 비교데이터 불러오기
비교 데이터(div, eps 등등) 가져오기
close #227 
- 관련된 이슈 번호를 연결해주세요.
=> feat: 주식 비교 데이터 가져오기 구현

src/main/java/org/scoula/nhapi/service/NhAccountServiceImpl.java, src/main/java/org/scoula/nhapi/service/NhCardServiceImpl.java, src/main/java/org/scoula/summary/controller/AssetSummaryController.java, src/main/java/org/scoula/summary/mapper/MonthlySnapshotMapper.java, src/main/java/org/scoula/summary/service/AssetSummaryService.java, src/main/java/org/scoula/summary/service/AssetSummaryServiceImpl.java, src/main/java/org/scoula/summary/service/MonthlySnapshotService.java, src/main/java/org/scoula/summary/service/MonthlySnapshotServiceImpl.java, src/main/java/org/scoula/summary/service/SpendingService.java, src/main/java/org/scoula/summary/service/SpendingServiceImpl.java, src/main/java/org/scoula/transactions/mapper/CardTransactionMapper.java, src/main/resources/org/scoula/summary/mapper/MonthlySnapshotMapper.xml, src/main/resources/org/scoula/transactions/mapper/AccountTransactionMapper.xml, src/main/resources/org/scoula/transactions/mapper/CardTransactionMapper.xml
총자산 계산식 및 집계 경로를 정확성/일관성/성능 중심으로 전면 정리
거래내역 기반 누적 대신 잔액/평가금액 스냅샷 기반으로 전환해 중복/누락/역산오차 제거
=> feat: total_asset 월말 계산 로직 수정

src/main/resources/org/scoula/finance/mapper/StockMapper.xml
주식 배당률 가져오기
주식 매퍼 수정
close #250 
- 관련된 이슈 번호를 연결해주세요.
=> feat: 주식 배당률 가져오기

src/main/resources/org/scoula/security/account/mapper/UserDetailsMapper.xml
로그인시 유저 응답값에 role 추가
admin 일 경우 관리자 페이지로 이동합니다
=> fix: 로그인시 유저 응답값에 role 추가

src/main/java/org/scoula/summary/dto/MonthlySnapshotDto.java
MonthlySnapshot 변수명 매핑 안 되던 것 수정
=> MonthlySnapshot 변수명 매핑 안 되던 것 수정

src/main/java/org/scoula/avatar/mapper/AvatarMapper.java, src/main/java/org/scoula/avatar/service/AvatarService.java, src/main/java/org/scoula/avatar/service/AvatarServiceImpl.java, src/main/resources/org/scoula/avatar/mapper/AvatarMapper.xml
아바타 착장 수정 관련 오류 해결
기존에 모든 착장을 명시해서 파라미터로 전달하지 않으면 nullPointException으로 오류가 나던 문제 해결 파라미터에 포함되지 않은 부위들을, avatar에서 NULL로 취급하도록 명시함
closes #263
=> fix: 아바타 착장 수정 오류 해결

src/main/java/org/scoula/ars/controller/ArsController.java, src/main/java/org/scoula/ars/domain/ArsVO.java, src/main/java/org/scoula/ars/dto/ArsDTO.java, src/main/java/org/scoula/ars/mapper/ArsMapper.java, src/main/java/org/scoula/ars/service/ArsService.java, src/main/java/org/scoula/ars/service/ArsServiceImpl.java, src/main/java/org/scoula/config/RootConfig.java, src/main/java/org/scoula/config/ServletConfig.java, src/main/resources/org/scoula/ars/mapper/ArsMapper.xml
ars에서 인증 시 입력하는 정보를 user테이블에 저장 및 조회하는 기능 추가
ars 인증 시 입력한 전화번호, 생년월일, 실명을 저장 및 조회하는 service와 controller, mapper 추가
closes #262
=> feat: ars인증 기능 추가

src/main/java/org/scoula/news/service/NewsServiceImpl.java
뉴스 키워드 수정
뉴스 키워드 랜덤선택 관련 수정
뉴스 키워드가 반환값에 포함되지 않는 현상 수정
closes #273
=> fix: 뉴스 키워드 수정
